Update new_test.yaml

diff --git a/.github/workflows/new_test.yaml b/.github/workflows/new_test.yaml
--- a/.github/workflows/new_test.yaml
+++ b/.github/workflows/new_test.yaml
@@ -221,19 +221,22 @@ jobs:
      - name: Sign Docker Image
        id: sign_docker_image
        run: |
-          echo "${{ secrets.COSIGN_KEY }}" | tr -d '\r' > cosign.key
-          chmod 600 cosign.key
-          
-          if cosign sign --key cosign.key ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} --yes; then
-            echo "Success:  Image sign successful."
-          else
-            echo "Error: Image sign failed."
-            exit 1
-          fi
+           echo "${{ secrets.COSIGN_KEY }}" | tr -d '\r' > cosign.key
+           chmod 600 cosign.key
+           
+           if cosign sign \
+              --key cosign.key \
+              --rekor-url http://52.172.140.64:3000/ \
+              ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} --yes; then
+             echo "Success: Image sign successful."
+           else
+             echo "Error: Image sign failed."
+             exit 1
+           fi
        env:
-          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
-          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
-          SIGSTORE_REKOR_URL: http://52.172.140.64:3000/
+           COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
+           COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
+
 
      - name: Public Key Creation
        id: create_public_key
