Update new_test.yaml

diff --git a/.github/workflows/new_test.yaml b/.github/workflows/new_test.yaml
--- a/.github/workflows/new_test.yaml
+++ b/.github/workflows/new_test.yaml
@@ -417,23 +417,12 @@ jobs:
         COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
 
-     # - name: Verify Provenance Attestation 
-     #   run: |
-     #    cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub --rekor-public-key rekor.pub --rekor-url https://85c8-52-172-140-64.ngrok-free.app ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} | jq -r .payload | base64 --decode | jq . || { echo "Error: Provenance Attestation  failed"; exit 1; }
-     #   shell: bash
-
-     - name: Verify Provenance Attestation
+     - name: Verify Provenance Attestation 
        run: |
-        export REKOR_PUBLIC_KEY=$(cat rekor.pub)
-        cosign verify-attestation \
-          --certificate-github-workflow-name=".github/workflows/cicd.yml@refs/heads/testing" \
-          --certificate-github-workflow-ref="refs/heads/testing" \
-          --certificate-github-workflow-repository="https://github.com/dheeman2912/spring-petclinic" \
-          --certificate-github-workflow-trigger="push" \
-          --key cosign.pub
-          --rekor-public-key rekor.pub\
-          --rekor-url https://85c8-52-172-140-64.ngrok-free.app \
-          ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} | jq -r .payload | base64 --decode | jq .
+        cosign verify-attestation --certificate-github-workflow-name=.github/workflows/cicd.yml@refs/heads/testing --certificate-github-workflow-ref=refs/heads/testing --certificate-github-workflow-repository=https://github.com/dheeman2912/spring-petclinic --certificate-github-workflow-trigger=push --key cosign.pub --key rekor.pub --rekor-url https://85c8-52-172-140-64.ngrok-free.app ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} | jq -r .payload | base64 --decode | jq . || { echo "Error: Provenance Attestation  failed"; exit 1; }
+       shell: bash
+
+  
 
 
   Image-Deploy:
