Update new_test.yaml

diff --git a/.github/workflows/new_test.yaml b/.github/workflows/new_test.yaml
--- a/.github/workflows/new_test.yaml
+++ b/.github/workflows/new_test.yaml
@@ -335,9 +335,9 @@ jobs:
        id: verify_sbom_signature
        run: |
           set -e
-          export REKOR_PUBLIC_KEY=$(cat rekor.pub)
           echo "sbom filename:$SBOM_FILENAME"
-          cosign verify --key cosign.pub ${{ secrets.IMAGE_NAME }}:$SBOM_FILENAME --rekor-url https://85c8-52-172-140-64.ngrok-free.app | jq . && { echo "Success: Verification of SBOM signature succesfull"; } || { echo "Error: Verification of SBOM signature failed"; exit 1; }
+          # cosign verify --key cosign.pub ${{ secrets.IMAGE_NAME }}:$SBOM_FILENAME --rekor-url https://85c8-52-172-140-64.ngrok-free.app | jq . && { echo "Success: Verification of SBOM signature succesfull"; } || { echo "Error: Verification of SBOM signature failed"; exit 1; }
+           cosign verify --key cosign.pub --rekor-url https://85c8-52-172-140-64.ngrok-free.app --rekor-public-key rekor.pub ${{ secrets.IMAGE_NAME }}:$SBOM_FILENAME | jq . && { echo "Success: Verification of SBOM signature successful"; } || { echo "Error: Verification of SBOM signature failed"; exit 1; }
 
      - name: Sign SBOM
        id: sign_sbom_blob
@@ -430,7 +430,8 @@ jobs:
           --certificate-github-workflow-ref="refs/heads/testing" \
           --certificate-github-workflow-repository="https://github.com/dheeman2912/spring-petclinic" \
           --certificate-github-workflow-trigger="push" \
-          --key cosign.pub \
+          --key cosign.pub
+          --rekor-public-key rekor.pub\
           --rekor-url https://85c8-52-172-140-64.ngrok-free.app \
           ${{ secrets.IMAGE_NAME }}@${{ env.IMAGE_SHA }} | jq -r .payload | base64 --decode | jq .
 
